### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by Rombersoft** [platisd/nokia-5110-lcd-library#1]
Hello friend, I began to use your library yesterday and was disappointed because I need cyrillic symbols. Can you help me to resolve my problem?

**Comment by platisd** [comment]
If you can provide all characters you need in a similar format to [this](https://github.com/platisd/nokia-5110-lcd-library/blob/master/src/Nokia_LCD_Fonts.h#L18) I can probably add the Cyrillic font.

**Comment by Rombersoft** [comment]
Yeah, it's that I need.

**Comment by Rombersoft** [comment]
Ok I done it self on Adafruit. Thanks

**Comment by platisd** [comment]
Good to hear! If it's something you think can benefit this project too feel free to create a pull request.
