### ISSUE TITLE
make ::printCharacter() public ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [platisd/nokia-5110-lcd-library#10]
hello,

I wanted to display `Serial.read()` directly using `lcd.printCharacter()` so I don't have to buffer serial data into a string, but it's private.

Is there a reason ?

Could you make it public in a next release ?

**Comment by platisd** [comment]
I can overload `print` to receive a `char`. How about that instead?

**Comment by SuperUserNameMan** [comment]
yep, that would be perfect :-)

**Comment by platisd** [comment]
I haven't tested it manually but it should work now with `print` and `println`.

**Comment by SuperUserNameMan** [comment]
works fine, thanks ! :-D
