### ISSUE TITLE
Compile error: 

### ISSUE THREAD

**Issue by Bavly9** [platisd/nokia-5110-lcd-library#14]
# A compile time error is showing up to me 

## In Nokia_LCD.cpp line 323: In member function 'bool Nokia_LCD::print(long unsigned int)'
variable-sized object 'number_as_string' may not be initialized 

    char number_as_string[length_as_string] = {0}; 

## This solution has worked for me 💯 
    char number_as_string[length_as_string];
    memset(  number_as_string, 0, length_as_string*sizeof(char) );

**Comment by platisd** [comment]
That sounds very strange as is the solution. What platform/board are you compiling for?

**Comment by platisd** [comment]
I do see the problem though. Let me know what platform you're using so I can reproduce the problem. The library is currently being verified against Arduino Uno and the ATtiny x5 microcontroller family.

**Comment by Bavly9** [comment]
I am compiling for wemos d1 mini, esp8266 based board.

**Comment by platisd** [comment]
Thanks, I will take a look!

**Comment by platisd** [comment]
I cannot reproduce the error when using the latest ESP8266 arduino core (3.0.1) and compiling for `LOLIN(WEMOS) D1 R2 & mini`.
Can you give more details on the exact steps to reproduce the problem?

**Comment by platisd** [comment]
In any case, can you please try out this branch: https://github.com/platisd/nokia-5110-lcd-library/tree/fix_variable_sized_array
It would be great if you can tell me if it fixes your problem and everything works as intended. :smile_cat:

**Comment by Bavly9** [comment]
Thanks alot @platisd , I updated the Esp8266 arduino core to the latest version and it works great 💯 💯 


![IMG_20210802_120608](https://user-images.githubusercontent.com/88204633/127845815-17b8b1f3-03da-4341-9bc5-5da568b92601.jpg)

**Comment by platisd** [comment]
Can you also try the branch out? The thing you discovered can potentially be a problem as it's not according to the C++ standard but many compilers support it.
