### ISSUE TITLE
Draw images of any size

### ISSUE THREAD

**Issue by jnthas** [platisd/nokia-5110-lcd-library#15]
Currently, the library is capable of drawing images, but it must be 84px wide or it will render incorrectly. (see example attached).

Creating another method `draw()` that receives the width of image should work.

Original image (size 42 x 30)
![square](https://user-images.githubusercontent.com/7151022/127792021-8e4d8742-f103-4749-9810-effca0a7611b.png)
Renderized on display
![IMG_20210801_221326](https://user-images.githubusercontent.com/7151022/127792131-6986bd91-c714-4253-888c-3b7da6f942d8.jpg)

**Comment by platisd** [comment]
Are you preparing a pull request? :)

**Comment by jnthas** [comment]
Yep, I'm trying to follow the "open source contribution protocol" :D 
The happy path is already working, I mean, when I have an image that fits on the screen on a correct position, it works. I will send a draft PR soon.

**Comment by platisd** [comment]
Cool, since you are at it, you may want to rebase to the latest `master`. Just pushed a small fix.
