### ISSUE TITLE
Example Nokia_LCD_Font doesn't compile if sketch is saved in sketchbook

### ISSUE THREAD

**Issue by zoomx** [platisd/nokia-5110-lcd-library#19]
Using IDE 1.8.19

Load the Nokia_LCD_Font example.
Click on Verify. It compiles.
Save it on sketchbook.
Click on Verify.
 You get error

Alternatives for fonts/Small_LCD_Fonts.h: []Nokia_LCD_Font:2:10: fatal error: fonts/Small_LCD_Fonts.h: No such file or directory

ResolveLibrary(fonts/Small_LCD_Fonts.h)
  -> candidates: []all_LCD_Fonts.h"

          ^~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
fonts/Small_LCD_Fonts.h: No such file or directory

**Comment by platisd** [comment]
Version `2.6.1` should fix this. Thanks for reporting! :+1:

**Comment by zoomx** [comment]
I believed that the fonts folder was in the library one, now I see that was in the example folder so when the example was saved the subfolder was not created.
Maybe you can move the fonts folder into the src library folder and change the include like this
#include <fonts/Bold_LCD_Fonts.h>
using <> instead of ""

**Comment by platisd** [comment]
Yes, that would work code-wise.
However the particular files are LGPL licensed by their original creator and I would like to keep them as separate as possible to be able to keep a permissive license (MIT) on the core library.
