### ISSUE TITLE
print(123.00) outputs "123.000" (extra 0 at the end)

### ISSUE THREAD

**Issue by JPTa** [platisd/nokia-5110-lcd-library#25]
https://github.com/platisd/nokia-5110-lcd-library/blob/cc069feab8c81ecf2b46c277cbcb8f0da7b2256c/src/Nokia_LCD.cpp#L374

When 'fractional' is zero it is not necessary to print it out at the end:

https://github.com/platisd/nokia-5110-lcd-library/blob/cc069feab8c81ecf2b46c277cbcb8f0da7b2256c/src/Nokia_LCD.cpp#L383

**Comment by platisd** [comment]
If I understood right, the proposed pull request (#26) will fix your issue. Do you agree?

**Comment by JPTa** [comment]
Yeah, that fixes it.

**Comment by platisd** [comment]
Thank you for reporting the issue :+1:
