### ISSUE TITLE
Error in print(float) function

### ISSUE THREAD

**Issue by MarcBousquet** [platisd/nokia-5110-lcd-library#6]
Hello,
If you want to print a float with a (various) '0' just after the coma, let say 9,0123, it ignores the 0 it means that 9.123, 9.0123 and 9.00123 will all be printing exactly the same.
reason is the way print(float) is implemented :

print(9.0123, 4) 
==> return print(9) || print(".") || print(0123);
==> return print(9) || print(".") || print(123);
==> 9.123

**Comment by MarcBousquet** [comment]
Proposal to solve it :

```
bool Nokia_LCD::print(double number, unsigned short decimals) {
    bool ret = true;
    double integral = 0;
    long fractional = pow(10.0, decimals) * modf(number, &integral);

    ret = print(static_cast<long>(number)) && ret;
    ret = print(".") && ret;
	
    for(int d=decimals-1 ; 0<=d; d-- ) {
	int num = fractional/pow(10, d);
	if (num) break; //print only leading 0s
	ret = print(num) && ret;
    }
		
    return print(fractional) && ret;
}
```

**Comment by platisd** [comment]
Can you please create a pull request with this?

**Comment by MarcBousquet** [comment]
I do not know how to proceed. i created my account yesterday to share this issue ;)
i tried but It looks like I need to have write access on the repository. From my understanding, a PR is to commit a change not to create a change request. that's why I would need write access

**Comment by platisd** [comment]
Oh, then it's a good chance to do your first open source contribution! :)

1. Create your personal copy of this repository by **fork**ing it (there's a button on the top right corner).
2. Push your changes to _your_ fork.
3. Create a **pull request** (GitHub will usually prompt you)

Then I will review your proposal and if it checks out it will be merged and you will have a proper attribution for the code you contributed. :+1:
